name: firecrawl

x-common-service: &common-service
  build:
    context: apps/api
    dockerfile: Dockerfile.unified
  networks:
    - backend
  environment:
    - NODE_ENV=development
    - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3003/scrape
    - NUM_WORKERS_PER_QUEUE=8
    - TEST_API_KEY=${TEST_API_KEY}
    - LOGGING_LEVEL=DEBUG
    - MAX_RAM=0.95
    - MAX_CPU=0.95
    # For local development, use Bull queue with Redis
    - QUEUE_PROVIDER=bull
    - REDIS_URL=redis://redis:6379
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  ulixee-service:
    image: firecrawl/ulixee-service
    build:
      context: ./apps/ulixee-service-ts/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PROXY_URL=${PROXY_URL}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - HERO_MAX_CONCURRENT_BROWSERS=10
      - ULIXEE_DATABOX_SIZE_MB=100
      - NODE_OPTIONS=--max-old-space-size=2048
      - CHROME_SANDBOX=false
      - RUNNING_IN_CLOUD=false
      - CHROME_PATH=/usr/bin/chromium
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped

  playwright-service:
    image: firecrawl/playwright-service
    build:
      context: ./apps/playwright-service-ts/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3003
      - PROXY_URL=${PROXY_URL}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - BLOCK_MEDIA=true
      - NODE_OPTIONS=--max-old-space-size=2048
      - CHROME_SANDBOX=false
    ports:
      - "3003:3003"
    networks:
      - backend
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped

  api:
    <<: *common-service
    depends_on:
      - redis
      - ulixee-service
      - playwright-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3003/scrape
      - NUM_WORKERS_PER_QUEUE=8
      - LOGGING_LEVEL=DEBUG
      - QUEUE_PROVIDER=bull
      - REDIS_URL=redis://redis:6379
    command: ["node", "dist/src/index.js"]

  worker:
    <<: *common-service
    depends_on:
      - redis
      - ulixee-service
      - playwright-service
      - api
    environment:
      - PORT=3004
      - NODE_ENV=development
      - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3003/scrape
      - NUM_WORKERS_PER_QUEUE=8
      - LOGGING_LEVEL=DEBUG
      - QUEUE_PROVIDER=bull
      - REDIS_URL=redis://redis:6379
    command: ["node", "dist/src/services/queue-worker.js"]

  redis:
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Optional Redis Commander for monitoring Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
